'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contacts
    Public Property PersonId As Integer
    Public Property ProviderId As Integer
    Public Property Title As String
    Public Property Id As Integer

    Public Overridable Property Person As People
    Public Overridable Property Providers As ICollection(Of Providers) = New HashSet(Of Providers)

End Class
