'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Location
    Public Property Id As Integer
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property Latitude As Nullable(Of Decimal)
    Public Property Longitude As Nullable(Of Decimal)

    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property Providers As ICollection(Of Provider) = New HashSet(Of Provider)
    Public Overridable Property ServiceCalls As ICollection(Of ServiceCall) = New HashSet(Of ServiceCall)

End Class
