'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class People
    Public Property Id As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Email As String

    Public Overridable Property Contacts As ICollection(Of Contacts) = New HashSet(Of Contacts)
    Public Overridable Property Customers As ICollection(Of Customers) = New HashSet(Of Customers)
    Public Overridable Property Phones As ICollection(Of Phones) = New HashSet(Of Phones)

End Class
