'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class RoadsideEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RoadsideEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Contacts1() As DbSet(Of Contacts)
    Public Overridable Property Customers1() As DbSet(Of Customers)
    Public Overridable Property Locations1() As DbSet(Of Locations)
    Public Overridable Property People1() As DbSet(Of People)
    Public Overridable Property Phones1() As DbSet(Of Phones)
    Public Overridable Property Providers1() As DbSet(Of Providers)
    Public Overridable Property ServiceCalls1() As DbSet(Of ServiceCalls)
    Public Overridable Property Statuses() As DbSet(Of Statuses)

End Class
