'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class RoadsideEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RoadsideEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Contacts() As DbSet(Of Contact)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Locations() As DbSet(Of Location)
    Public Overridable Property People() As DbSet(Of Person)
    Public Overridable Property Phones() As DbSet(Of Phone)
    Public Overridable Property Providers() As DbSet(Of Provider)
    Public Overridable Property ServiceCalls() As DbSet(Of ServiceCall)
    Public Overridable Property Statuses() As DbSet(Of Status)

End Class
