'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServiceCalls
    Public Property Id As Integer
    Public Property TimeOf As Date
    Public Property CustomerID As Integer
    Public Property Contract As String
    Public Property Equipment As String
    Public Property Issue As String
    Public Property Description As String
    Public Property LocationID As Integer

    Public Overridable Property Customer As Customers
    Public Overridable Property Location As Locations
    Public Overridable Property Statuses As ICollection(Of Statuses) = New HashSet(Of Statuses)

End Class
